# Generated by Django 5.1.5 on 2025-03-12 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('KhachHangID', models.AutoField(primary_key=True, serialize=False)),
                ('HoTenKhachHang', models.CharField(max_length=100)),
                ('NgaySinh', models.DateField()),
                ('GioiTinh', models.CharField(max_length=5)),
                ('CongViec', models.CharField(max_length=100)),
                ('TinhThanh', models.CharField(max_length=100)),
                ('QuanHuyen', models.CharField(max_length=100)),
                ('PhuongXa', models.CharField(max_length=100)),
                ('DiaChiCuThe', models.CharField(max_length=255)),
                ('SoCCCD', models.CharField(max_length=12)),
                ('NgayCapCCCD', models.DateField()),
                ('NoiCapCCCD', models.CharField(max_length=100)),
                ('CCCDMT', models.ImageField(upload_to='images/')),
                ('CCCDMS', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Phong',
            fields=[
                ('PhongID', models.AutoField(primary_key=True, serialize=False)),
                ('SoPhong', models.CharField(max_length=100)),
                ('DayPhong', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=1)),
                ('GiaPhong', models.DecimalField(decimal_places=2, max_digits=10)),
                ('TrangThaiPhong', models.CharField(choices=[('ConTrong', 'Còn trống'), ('DaThue', 'Đã thuê')], max_length=50)),
                ('MoTaPhong', models.TextField()),
                ('DienTich', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='QuanLi',
            fields=[
                ('QuanLiID', models.AutoField(primary_key=True, serialize=False)),
                ('SoDienThoaiDN', models.CharField(max_length=15, unique=True)),
                ('MatKhauDN', models.CharField(max_length=100)),
                ('HoTenQuanLi', models.CharField(max_length=100)),
                ('failed_attempts', models.IntegerField(default=0)),
                ('lockout_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhiPhatSinh',
            fields=[
                ('PhatSinhID', models.AutoField(primary_key=True, serialize=False)),
                ('DayPhong', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=1)),
                ('TenPhatSinh', models.CharField(max_length=100)),
                ('GiaPhatSinh', models.DecimalField(decimal_places=2, max_digits=10)),
                ('MoTaPhatSinh', models.TextField()),
                ('ThangNam', models.CharField(max_length=7)),
                ('PhongID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.phong')),
            ],
        ),
        migrations.CreateModel(
            name='HopDong',
            fields=[
                ('HopDongID', models.AutoField(primary_key=True, serialize=False)),
                ('DayPhong', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=1)),
                ('NgayBatDau', models.DateField()),
                ('NgayKetThuc', models.DateField()),
                ('ChuKy', models.CharField(default='1 tháng', max_length=100)),
                ('TienDatCoc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('TrangThaiHopDong', models.CharField(choices=[('HoatDong', 'Hoạt động'), ('HetHan', 'Hết hạn')], max_length=50)),
                ('NgayTaoHopDong', models.DateField(auto_now_add=True)),
                ('KhachHangID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.khachhang')),
                ('PhongID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.phong')),
            ],
        ),
        migrations.CreateModel(
            name='ChiSoDienNuoc',
            fields=[
                ('ChiSoID', models.AutoField(primary_key=True, serialize=False)),
                ('DayPhong', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=1)),
                ('ThangNam', models.CharField(blank=True, max_length=7, null=True)),
                ('ChiSoDienCu', models.IntegerField(blank=True, null=True)),
                ('ChiSoNuocCu', models.IntegerField(blank=True, null=True)),
                ('ChiSoDienMoi', models.IntegerField(blank=True, null=True)),
                ('ChiSoNuocMoi', models.IntegerField(blank=True, null=True)),
                ('SoDienDaTieuThu', models.IntegerField(blank=True, null=True)),
                ('SoNuocDaTieuThu', models.IntegerField(blank=True, null=True)),
                ('TongTienDien', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('TongTienNuoc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('TienPhong', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('TongPhiPhatSinh', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('TongTien', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('TrangThaiThanhToan', models.CharField(blank=True, max_length=1, null=True)),
                ('Tientra', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('TienNo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('PhongID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_so_dien_nuoc', to='myapp.phong')),
            ],
        ),
        migrations.CreateModel(
            name='ThanhToan',
            fields=[
                ('ThanhToanID', models.AutoField(primary_key=True, serialize=False)),
                ('SoTienThanhToan', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PhuongThucThanhToan', models.CharField(choices=[('TienMat', 'Tiền mặt'), ('ChuyenKhoan', 'Chuyển khoản'), ('VNPay', 'VNPay'), ('MOMO', 'MOMO')], max_length=50)),
                ('MaGiaoDich', models.CharField(blank=True, max_length=100, null=True)),
                ('TrangThaiGiaoDich', models.CharField(choices=[('ThanhCong', 'Thành công'), ('ThatBai', 'Thất bại'), ('ChoXuLy', 'Chờ xử lý')], default='ChoXuLy', max_length=20)),
                ('NoiDungThanhToan', models.CharField(blank=True, max_length=255, null=True)),
                ('NgayThanhToan', models.DateTimeField(auto_now_add=True)),
                ('ResponseData', models.JSONField(blank=True, null=True)),
                ('ChiSoDienNuocID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.chisodiennuoc')),
                ('HopDongID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.hopdong')),
                ('KhachHangID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.khachhang')),
                ('PhongID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.phong')),
            ],
        ),
        migrations.CreateModel(
            name='LichSuGiaoDich',
            fields=[
                ('LichSuID', models.AutoField(primary_key=True, serialize=False)),
                ('NgayThanhToan', models.DateTimeField(auto_now_add=True)),
                ('SoTienDaThanhToan', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PhuongThucThanhToan', models.CharField(choices=[('TienMat', 'Tiền mặt'), ('ChuyenKhoan', 'Chuyển khoản'), ('VNPay', 'VNPay'), ('MOMO', 'MOMO')], max_length=50)),
                ('MaGiaoDich', models.CharField(blank=True, max_length=100, null=True)),
                ('TrangThaiGiaoDich', models.CharField(choices=[('ThanhCong', 'Thành công'), ('ThatBai', 'Thất bại'), ('ChoXuLy', 'Chờ xử lý')], default='ChoXuLy', max_length=20)),
                ('ThanhToanID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.thanhtoan')),
            ],
        ),
    ]
