# Generated by Django 5.1.5 on 2025-03-14 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_phong_dientich'),
    ]

    operations = [
        migrations.AddField(
            model_name='khachhang',
            name='SoDienThoai',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
