# Generated by Django 5.1.5 on 2025-03-14 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_khachhang_sodienthoai'),
    ]

    operations = [
        migrations.AddField(
            model_name='phong',
            name='TienIch',
            field=models.JSONField(default=list),
        ),
    ]
