# Generated by Django 5.1.5 on 2025-03-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_phong_tienich'),
    ]

    operations = [
        migrations.AddField(
            model_name='quanli',
            name='DiaChiChiTiet',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quanli',
            name='GioiTinh',
            field=models.CharField(blank=True, choices=[('Nam', 'Nam'), ('Nữ', 'Nữ')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='quanli',
            name='NgaySinh',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quanli',
            name='Phuong',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quanli',
            name='Quan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quanli',
            name='SoCCCD',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='quanli',
            name='ThanhPho',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
