# Generated by Django 5.1.5 on 2025-03-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_quanli_diachichitiet_quanli_gioitinh_quanli_ngaysinh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hopdong',
            name='GhiChuHopDong',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hopdong',
            name='SoLuongThanhVien',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='hopdong',
            name='SoTienPhong',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='hopdong',
            name='ThoiHanHopDong',
            field=models.CharField(blank=True, choices=[('3 tháng', '3 tháng'), ('6 tháng', '6 tháng'), ('8 tháng', '8 tháng'), ('1 năm', '1 năm'), ('2 năm', '2 năm'), ('3 năm', '3 năm'), ('4 năm', '4 năm'), ('5 năm', '5 năm'), ('6 năm', '6 năm')], max_length=50, null=True),
        ),
    ]
