# Generated by Django 5.1.5 on 2025-03-19 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_hopdong_ghichuhopdong_hopdong_soluongthanhvien_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaiKhoan',
            fields=[
                ('TaiKhoanID', models.AutoField(primary_key=True, serialize=False)),
                ('TenDangNhap', models.CharField(max_length=50, unique=True)),
                ('MatKhau', models.CharField(max_length=50)),
                ('NgayTao', models.DateTimeField(auto_now_add=True)),
                ('TrangThai', models.CharField(choices=[('HoatDong', 'Hoạt động'), ('Khoa', 'Khóa'), ('Xoa', 'Xóa')], default='HoatDong', max_length=20)),
                ('KhachHangID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tai_khoan', to='myapp.khachhang')),
            ],
            options={
                'verbose_name': 'Tài khoản',
                'verbose_name_plural': 'Tài khoản',
                'db_table': 'TaiKhoan',
            },
        ),
    ]
