# Generated by Django 5.1.5 on 2025-03-19 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_taikhoan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taikhoan',
            options={},
        ),
        migrations.AlterModelTable(
            name='taikhoan',
            table=None,
        ),
    ]
