# Generated by Django 5.1.5 on 2025-03-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_taikhoan_options_alter_taikhoan_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='taikhoan',
            name='Email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
