# Generated by Django 5.1.5 on 2025-03-19 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_taikhoan_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phiphatsinh',
            name='DayPhong',
        ),
        migrations.RemoveField(
            model_name='phiphatsinh',
            name='PhongID',
        ),
    ]
