# Generated by Django 5.1.5 on 2025-03-21 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_phiphatsinh_dayphong_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hopdong',
            name='SoTienPhong',
        ),
    ]
