# Generated by Django 5.1.5 on 2025-03-21 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_hopdong_sotienphong'),
    ]

    operations = [
        migrations.CreateModel(
            name='DichVu',
            fields=[
                ('DichVuID', models.AutoField(primary_key=True, serialize=False)),
                ('TenDichVu', models.CharField(max_length=100)),
                ('GiaDichVu', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='PhiPhatSinh',
        ),
    ]
