# Generated by Django 5.1.5 on 2025-03-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_dichvu_delete_phiphatsinh'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chisodiennuoc',
            old_name='TongPhiPhatSinh',
            new_name='TongDichVu',
        ),
        migrations.AddField(
            model_name='dichvu',
            name='GiaCuCuDichVu',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
