# Generated by Django 5.1.5 on 2025-03-21 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_rename_tongphiphatsinh_chisodiennuoc_tongdichvu_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dichvu',
            old_name='GiaCuCuDichVu',
            new_name='GiaCuDichVu',
        ),
    ]
