# Generated by Django 5.1.5 on 2025-03-21 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_rename_giacucudichvu_dichvu_giacudichvu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dichvu',
            name='GiaCuDichVu',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dichvu',
            name='GiaDichVu',
            field=models.IntegerField(),
        ),
    ]
