# Generated by Django 5.1.5 on 2025-03-21 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_dichvu_giacudichvu_alter_dichvu_giadichvu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chisodiennuoc',
            old_name='TongTienDien',
            new_name='GiaDienCu',
        ),
        migrations.RenameField(
            model_name='chisodiennuoc',
            old_name='TongTienNuoc',
            new_name='GiaDienMoi',
        ),
        migrations.RemoveField(
            model_name='chisodiennuoc',
            name='SoDienDaTieuThu',
        ),
        migrations.RemoveField(
            model_name='chisodiennuoc',
            name='SoNuocDaTieuThu',
        ),
        migrations.AddField(
            model_name='chisodiennuoc',
            name='GiaNuocCu',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='chisodiennuoc',
            name='GiaNuocMoi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
