# Generated by Django 5.1.5 on 2025-03-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_chisodiennuoc_sodiendatieuthu_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiaDienNuoc',
            fields=[
                ('GiaID', models.AutoField(primary_key=True, serialize=False)),
                ('LoaiDichVu', models.CharField(choices=[('Dien', 'Điện'), ('Nuoc', 'Nước')], max_length=10)),
                ('GiaCu', models.IntegerField(blank=True, null=True)),
                ('GiaMoi', models.IntegerField()),
                ('NgayCapNhat', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-NgayCapNhat'],
            },
        ),
    ]
