# Generated by Django 5.1.7 on 2025-03-25 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_giadiennuoc'),
    ]

    operations = [
        migrations.AddField(
            model_name='hopdong',
            name='QuanLiID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.quanli'),
        ),
    ]
