# Generated by Django 5.1.7 on 2025-03-27 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_hopdong_quanliid'),
    ]

    operations = [
        migrations.CreateModel(
            name='LienHe',
            fields=[
                ('LienHeID', models.AutoField(primary_key=True, serialize=False)),
                ('LyDoLienHe', models.CharField(max_length=100)),
                ('NoiDung', models.TextField()),
                ('TrangThai', models.CharField(blank=True, max_length=15, null=True)),
                ('KhachHangID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.khachhang')),
                ('PhongID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.phong')),
            ],
        ),
    ]
