# Generated by Django 5.1.7 on 2025-03-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_lienhe'),
    ]

    operations = [
        migrations.AddField(
            model_name='lienhe',
            name='Time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
